import { assertEquals } from "@std/assert";
import { RoofMap } from "../08.ts";

Deno.test(function day08Test() {
    const input = `
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    `;

    const map = RoofMap.fromInput(input);

    assertEquals(map.antinodes(false).uniquePositions().length, 14);
    assertEquals(map.antinodes(true).uniquePositions().length, 34);
});